// <auto-generated />
using H3GUIAPI.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace H3GUIAPI.API.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20260303004247_fsdfds")]
    partial class fsdfds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("H3GUIAPI.API.Models.Category", b =>
                {
                    b.Property<uint>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1u,
                            Title = "Cooking"
                        },
                        new
                        {
                            CategoryId = 2u,
                            Title = "Self Help"
                        },
                        new
                        {
                            CategoryId = 3u,
                            Title = "Coding"
                        },
                        new
                        {
                            CategoryId = 4u,
                            Title = "Fitness"
                        },
                        new
                        {
                            CategoryId = 5u,
                            Title = "Romancd"
                        },
                        new
                        {
                            CategoryId = 6u,
                            Title = "Horror"
                        });
                });

            modelBuilder.Entity("H3GUIAPI.API.Models.ImageFilePageData", b =>
                {
                    b.Property<int>("ImageFilePathDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImageFilePathDataId");

                    b.HasIndex("RelativePath")
                        .IsUnique();

                    b.ToTable("ImageFilesDatas");
                });

            modelBuilder.Entity("H3GUIAPI.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageFilePageDataId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageFilePageDataId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("H3GUIAPI.API.Models.Product", b =>
                {
                    b.HasOne("H3GUIAPI.API.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("H3GUIAPI.API.Models.ImageFilePageData", "ImageFilePageData")
                        .WithMany()
                        .HasForeignKey("ImageFilePageDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ImageFilePageData");
                });
#pragma warning restore 612, 618
        }
    }
}
